name: cast
description: Dart package to discover and connect with Chromecast devices
version: 1.1.2
homepage: hhttps://github.com/jan-milovanovic/flutter_cast

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bonsoir: ^2.0.0
  flutter:
    sdk: flutter
  protobuf: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  protoc_plugin: ^20.0.1
